=== funIntentions/flow/data/SmartGridTemplate.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="stringType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="intType">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="decType">
        <xs:restriction base="xs:decimal"/>
    </xs:simpleType>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="STRING"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="storageStrategyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TEST_ONE"/>
            <xs:enumeration value="TEST_TWO"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="structureType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SINGLE_UNIT"/>
            <xs:enumeration value="COMPOSITE_UNIT"/>
            <xs:enumeration value="POWER_PLANT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="imageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="HOUSE_IMAGE"/>
            <xs:enumeration value="POWER_PLANT_IMAGE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="genericType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="dataType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="timeSpanType">
        <xs:sequence>
            <xs:element name="from" type="decType"/>
            <xs:element name="to" type="decType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="value" type="genericType"/>
            <xs:element name="units" type="stringType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="timeSpanListType">
        <xs:sequence>
            <xs:element name="timeSpan" type="timeSpanType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="propertyListType">
        <xs:sequence>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="applianceListType">
        <xs:sequence>
            <xs:element name="appliance" type="applianceTemplate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="energySourceListType">
        <xs:sequence>
            <xs:element name="energySource" type="energyStorageTemplate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="energyStorageListType">
        <xs:sequence>
            <xs:element name="energyStorageDevice" type="energyStorageTemplate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="applianceTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
            <xs:element name="standbyConsumption" type="decType"/>
            <xs:element name="usageConsumption" type="decType"/>
            <xs:element name="timeSpans" type="timeSpanListType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="energyStorageTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
            <xs:element name="chargeDischargeRate" type="decType"/>
            <xs:element name="storageCapacity" type="decType"/>
            <xs:element name="storageStrategy" type="storageStrategyType"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="energySourceTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="simpleStructureTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
            <xs:element name="type" type="structureType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="appliances" type="applianceListType"/>
            <xs:element name="energySources" type="energySourceListType"/>
            <xs:element name="energyStorageDevices" type="energyStorageListType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="compositeStructureTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
            <xs:element name="type" type="structureType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="numberOfUnits" type="intType"/>
            <xs:element name="appliances" type="applianceListType"/>
            <xs:element name="energySources" type="energySourceListType"/>
            <xs:element name="energyStorageDevices" type="energyStorageListType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="powerPlantTemplate">
        <xs:sequence>
            <xs:element name="name" type="stringType"/>
            <xs:element name="id" type="intType"/>
            <xs:element name="type" type="structureType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="emissionRate" type="decType"/>
            <xs:element name="cost" type="decType"/>
            <xs:element name="capacity" type="decType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="smartGrid">
        <xs:complexType>
            <xs:all>
                <xs:element name="templateStructures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="simpleStructure" type="simpleStructureTemplate" maxOccurs="unbounded"/>
                            <xs:element name="compositeStructure" type="compositeStructureTemplate" maxOccurs="unbounded"/>
                            <xs:element name="powerPlant" type="powerPlantTemplate" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="worldStructures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="simpleStructure" type="simpleStructureTemplate" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="compositeStructure" type="compositeStructureTemplate" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="powerPlant" type="powerPlantTemplate" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== funIntentions/flow/data/SmartGridTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<smartGrid
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="SmartGridTemplate.xsd">
    <template>
        <structure>
            <name>Coal Power Plant</name>
            <id>-1</id>
            <type>POWER_PLANT</type>
            <image>POWER_PLANT_IMAGE</image>
            <numberOfUnits>1</numberOfUnits>
            <properties>
                <property>
                    <name>X Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
                <property>
                    <name>Y Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
                <property>
                    <name>Emission Rate</name>
                    <value type="DOUBLE">600.0</value>
                    <units>g/kWh</units>
                </property>
                <property>
                    <name>Production Cost</name>
                    <value type="DOUBLE">0.06</value>
                    <units>$/kWh</units>
                </property>
                <property>
                    <name>Capacity</name>
                    <value type="DOUBLE">4000.0</value>
                    <units>W</units>
                </property>
            </properties>
            <appliances/>
            <energySources/>
            <energyStorageDevices/>
        </structure>
        <structure>
            <name>Solar Farm</name>
            <id>-1</id>
            <type>POWER_PLANT</type>
            <image>POWER_PLANT_IMAGE</image>
            <numberOfUnits>1</numberOfUnits>
            <properties>
                <property>
                    <name>X Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
                <property>
                    <name>Y Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
                <property>
                    <name>Emission Rate</name>
                    <value type="DOUBLE">100.0</value>
                    <units>g/kWh</units>
                </property>
                <property>
                    <name>Production Cost</name>
                    <value type="DOUBLE">0.5</value>
                    <units>$/kWh</units>
                </property>
                <property>
                    <name>Capacity</name>
                    <value type="DOUBLE">1000.0</value>
                    <units>W</units>
                </property>
            </properties>
            <appliances/>
            <energySources/>
            <energyStorageDevices/>
        </structure>
        <structure>
            <name>Summer Home</name>
            <id>-1</id>
            <type>SINGLE_UNIT</type>
            <image>HOUSE_IMAGE</image>
            <numberOfUnits>1</numberOfUnits>
            <properties>
                <property>
                    <name>X Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
                <property>
                    <name>Y Coordinate</name>
                    <value type="INTEGER">0</value>
                    <units> </units>
                </property>
            </properties>
            <appliances>
                <device>
                    <name>Portable Fan</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">115.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>61200.0</from>
                            <to>72000.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Continuous Furnace Fan Motor</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">350.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>0.0</from>
                            <to>86340.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Central Air Conditioning</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">3500.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>43200.0</from>
                            <to>68400.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Dishwasher</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">1300.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>70200.0</from>
                            <to>72000.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Fridge</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">500.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>25200.0</from>
                            <to>30600.0</to>
                        </timeSpan>
                        <timeSpan>
                            <from>43200.0</from>
                            <to>50400.0</to>
                        </timeSpan>
                        <timeSpan>
                            <from>66600.0</from>
                            <to>72000.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Television</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
                            <name>Usage Consumption</name>
                            <value type="DOUBLE">100.0</value>
                            <units>W</units>
                        </property>
                    </properties>
                    <timeSpans>
                        <timeSpan>
                            <from>61200.0</from>
                            <to>82800.0</to>
                        </timeSpan>
                    </timeSpans>
                </device>
                <device>
                    <name>Stove</name>
                    <id>-1</id>
                    <type>APPLIANCE</type>
                    <properties>
                        <property>
                            <name>Standby Consumption</name>
                            <value type="DOUBLE">0.0</value>
                            <units>W</units>
                        </property>
                        <property>
